//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsRelanzamientoServiceCustomers.ServicioCustomers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.praxair.com.co/customer", ConfigurationName="ServicioCustomers.IWS_Customers")]
    public interface IWS_Customers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praxair.com.co/customer/IWS_Customers/Confirmation", ReplyAction="http://www.praxair.com.co/customer/IWS_Customers/ConfirmationResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] Confirmation(int companyID, string customerID, string interfaceStatus, string an8);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praxair.com.co/customer/IWS_Customers/Get_Customers", ReplyAction="http://www.praxair.com.co/customer/IWS_Customers/Get_CustomersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] Get_Customers(string interfaceStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWS_CustomersChannel : WindowsRelanzamientoServiceCustomers.ServicioCustomers.IWS_Customers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_CustomersClient : System.ServiceModel.ClientBase<WindowsRelanzamientoServiceCustomers.ServicioCustomers.IWS_Customers>, WindowsRelanzamientoServiceCustomers.ServicioCustomers.IWS_Customers {
        
        public WS_CustomersClient() {
        }
        
        public WS_CustomersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_CustomersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_CustomersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_CustomersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object[] Confirmation(int companyID, string customerID, string interfaceStatus, string an8) {
            return base.Channel.Confirmation(companyID, customerID, interfaceStatus, an8);
        }
        
        public object[] Get_Customers(string interfaceStatus) {
            return base.Channel.Get_Customers(interfaceStatus);
        }
    }
}
