//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Customers.ServicioCustomerPraxReqABCSImp {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://praxair.com/PraxairBusinessFault")]
    public partial class PraxairBusinessFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string detailField;
        
        private string summaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://praxair.com/PraxairBusinessFault", ConfigurationName="ServicioCustomerPraxReqABCSImp.PraxairBusinessFaultPortType")]
    public interface PraxairBusinessFaultPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación process no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="process", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFault), Action="process", Name="PraxairBusinessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest process(WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://praxair.com/PraxairBusinessFault", Order=0)]
        public WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFault PraxairBusinessFault;
        
        public processRequest() {
        }
        
        public processRequest(WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFault PraxairBusinessFault) {
            this.PraxairBusinessFault = PraxairBusinessFault;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PraxairBusinessFaultPortTypeChannel : WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFaultPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PraxairBusinessFaultPortTypeClient : System.ServiceModel.ClientBase<WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFaultPortType>, WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFaultPortType {
        
        public PraxairBusinessFaultPortTypeClient() {
        }
        
        public PraxairBusinessFaultPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PraxairBusinessFaultPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PraxairBusinessFaultPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PraxairBusinessFaultPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFaultPortType.process(WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest request) {
            return base.Channel.process(request);
        }
        
        public void process(ref WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFault PraxairBusinessFault) {
            WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest inValue = new WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest();
            inValue.PraxairBusinessFault = PraxairBusinessFault;
            WCF_Customers.ServicioCustomerPraxReqABCSImp.processRequest retVal = ((WCF_Customers.ServicioCustomerPraxReqABCSImp.PraxairBusinessFaultPortType)(this)).process(inValue);
            PraxairBusinessFault = retVal.PraxairBusinessFault;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/ABCSImpl/Prax/Core/SyncCustomerPraxReqABCSImpl/V1", ConfigurationName="ServicioCustomerPraxReqABCSImp.SyncCustomerPraxReqABCSImpl")]
    public interface SyncCustomerPraxReqABCSImpl {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SyncCustomer no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="SyncCustomer")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SyncCustomer(WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomer request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.praxair.com.co/customer")]
    public partial class CUSTOMERS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CUSTOMERSADDRESSBOOK aDDRESSBOOKField;
        
        private CUSTOMERSCOLOMBIA_ADICIONAL_INFORMACION cOLOMBIA_ADICIONAL_INFORMACIONField;
        
        private CUSTOMERSCUSTOMERMASTER cUSTOMERMASTERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CUSTOMERSADDRESSBOOK ADDRESSBOOK {
            get {
                return this.aDDRESSBOOKField;
            }
            set {
                this.aDDRESSBOOKField = value;
                this.RaisePropertyChanged("ADDRESSBOOK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CUSTOMERSCOLOMBIA_ADICIONAL_INFORMACION COLOMBIA_ADICIONAL_INFORMACION {
            get {
                return this.cOLOMBIA_ADICIONAL_INFORMACIONField;
            }
            set {
                this.cOLOMBIA_ADICIONAL_INFORMACIONField = value;
                this.RaisePropertyChanged("COLOMBIA_ADICIONAL_INFORMACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CUSTOMERSCUSTOMERMASTER CUSTOMERMASTER {
            get {
                return this.cUSTOMERMASTERField;
            }
            set {
                this.cUSTOMERMASTERField = value;
                this.RaisePropertyChanged("CUSTOMERMASTER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.praxair.com.co/customer")]
    public partial class CUSTOMERSADDRESSBOOK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aN8Field;
        
        private string coField;
        
        private string eXR1Field;
        
        private string mCUField;
        
        private string tAXField;
        
        private string aLPHField;
        
        private string aT1Field;
        
        private string aLKYField;
        
        private string sICField;
        
        private string lNGPField;
        
        private string tAXCField;
        
        private string aC01Field;
        
        private string aC04Field;
        
        private string aC16Field;
        
        private string aC11Field;
        
        private string aC12Field;
        
        private string aC13Field;
        
        private string mLNMField;
        
        private string aDD1Field;
        
        private string aDD2Field;
        
        private string cTY1Field;
        
        private string cTRField;
        
        private string aDDSField;
        
        private string cOUNField;
        
        private string pH1Field;
        
        private string pA8Field;
        
        private string aC18Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AN8 {
            get {
                return this.aN8Field;
            }
            set {
                this.aN8Field = value;
                this.RaisePropertyChanged("AN8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CO {
            get {
                return this.coField;
            }
            set {
                this.coField = value;
                this.RaisePropertyChanged("CO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EXR1 {
            get {
                return this.eXR1Field;
            }
            set {
                this.eXR1Field = value;
                this.RaisePropertyChanged("EXR1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MCU {
            get {
                return this.mCUField;
            }
            set {
                this.mCUField = value;
                this.RaisePropertyChanged("MCU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TAX {
            get {
                return this.tAXField;
            }
            set {
                this.tAXField = value;
                this.RaisePropertyChanged("TAX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ALPH {
            get {
                return this.aLPHField;
            }
            set {
                this.aLPHField = value;
                this.RaisePropertyChanged("ALPH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AT1 {
            get {
                return this.aT1Field;
            }
            set {
                this.aT1Field = value;
                this.RaisePropertyChanged("AT1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ALKY {
            get {
                return this.aLKYField;
            }
            set {
                this.aLKYField = value;
                this.RaisePropertyChanged("ALKY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SIC {
            get {
                return this.sICField;
            }
            set {
                this.sICField = value;
                this.RaisePropertyChanged("SIC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LNGP {
            get {
                return this.lNGPField;
            }
            set {
                this.lNGPField = value;
                this.RaisePropertyChanged("LNGP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TAXC {
            get {
                return this.tAXCField;
            }
            set {
                this.tAXCField = value;
                this.RaisePropertyChanged("TAXC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AC01 {
            get {
                return this.aC01Field;
            }
            set {
                this.aC01Field = value;
                this.RaisePropertyChanged("AC01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AC04 {
            get {
                return this.aC04Field;
            }
            set {
                this.aC04Field = value;
                this.RaisePropertyChanged("AC04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AC16 {
            get {
                return this.aC16Field;
            }
            set {
                this.aC16Field = value;
                this.RaisePropertyChanged("AC16");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AC11 {
            get {
                return this.aC11Field;
            }
            set {
                this.aC11Field = value;
                this.RaisePropertyChanged("AC11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AC12 {
            get {
                return this.aC12Field;
            }
            set {
                this.aC12Field = value;
                this.RaisePropertyChanged("AC12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AC13 {
            get {
                return this.aC13Field;
            }
            set {
                this.aC13Field = value;
                this.RaisePropertyChanged("AC13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string MLNM {
            get {
                return this.mLNMField;
            }
            set {
                this.mLNMField = value;
                this.RaisePropertyChanged("MLNM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ADD1 {
            get {
                return this.aDD1Field;
            }
            set {
                this.aDD1Field = value;
                this.RaisePropertyChanged("ADD1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ADD2 {
            get {
                return this.aDD2Field;
            }
            set {
                this.aDD2Field = value;
                this.RaisePropertyChanged("ADD2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CTY1 {
            get {
                return this.cTY1Field;
            }
            set {
                this.cTY1Field = value;
                this.RaisePropertyChanged("CTY1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CTR {
            get {
                return this.cTRField;
            }
            set {
                this.cTRField = value;
                this.RaisePropertyChanged("CTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ADDS {
            get {
                return this.aDDSField;
            }
            set {
                this.aDDSField = value;
                this.RaisePropertyChanged("ADDS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string COUN {
            get {
                return this.cOUNField;
            }
            set {
                this.cOUNField = value;
                this.RaisePropertyChanged("COUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string PH1 {
            get {
                return this.pH1Field;
            }
            set {
                this.pH1Field = value;
                this.RaisePropertyChanged("PH1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PA8 {
            get {
                return this.pA8Field;
            }
            set {
                this.pA8Field = value;
                this.RaisePropertyChanged("PA8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string AC18 {
            get {
                return this.aC18Field;
            }
            set {
                this.aC18Field = value;
                this.RaisePropertyChanged("AC18");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.praxair.com.co/customer")]
    public partial class CUSTOMERSCOLOMBIA_ADICIONAL_INFORMACION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string v076CTPTField;
        
        private System.DateTime v0EFDJField;
        
        private string v076CCIIUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string V076CTPT {
            get {
                return this.v076CTPTField;
            }
            set {
                this.v076CTPTField = value;
                this.RaisePropertyChanged("V076CTPT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime V0EFDJ {
            get {
                return this.v0EFDJField;
            }
            set {
                this.v0EFDJField = value;
                this.RaisePropertyChanged("V0EFDJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string V076CCIIU {
            get {
                return this.v076CCIIUField;
            }
            set {
                this.v076CCIIUField = value;
                this.RaisePropertyChanged("V076CCIIU");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.praxair.com.co/customer")]
    public partial class CUSTOMERSCUSTOMERMASTER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tXA1Field;
        
        private string cRCAField;
        
        private int aCLField;
        
        private string rYINField;
        
        private string cRCDField;
        
        private string tRARField;
        
        private string cLMGField;
        
        private System.DateTime dAOJField;
        
        private string aC30Field;
        
        private string aBC1Field;
        
        private string bADTField;
        
        private string aCTNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TXA1 {
            get {
                return this.tXA1Field;
            }
            set {
                this.tXA1Field = value;
                this.RaisePropertyChanged("TXA1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CRCA {
            get {
                return this.cRCAField;
            }
            set {
                this.cRCAField = value;
                this.RaisePropertyChanged("CRCA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ACL {
            get {
                return this.aCLField;
            }
            set {
                this.aCLField = value;
                this.RaisePropertyChanged("ACL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RYIN {
            get {
                return this.rYINField;
            }
            set {
                this.rYINField = value;
                this.RaisePropertyChanged("RYIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CRCD {
            get {
                return this.cRCDField;
            }
            set {
                this.cRCDField = value;
                this.RaisePropertyChanged("CRCD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TRAR {
            get {
                return this.tRARField;
            }
            set {
                this.tRARField = value;
                this.RaisePropertyChanged("TRAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CLMG {
            get {
                return this.cLMGField;
            }
            set {
                this.cLMGField = value;
                this.RaisePropertyChanged("CLMG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime DAOJ {
            get {
                return this.dAOJField;
            }
            set {
                this.dAOJField = value;
                this.RaisePropertyChanged("DAOJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AC30 {
            get {
                return this.aC30Field;
            }
            set {
                this.aC30Field = value;
                this.RaisePropertyChanged("AC30");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ABC1 {
            get {
                return this.aBC1Field;
            }
            set {
                this.aBC1Field = value;
                this.RaisePropertyChanged("ABC1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BADT {
            get {
                return this.bADTField;
            }
            set {
                this.bADTField = value;
                this.RaisePropertyChanged("BADT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ACTN {
            get {
                return this.aCTNField;
            }
            set {
                this.aCTNField = value;
                this.RaisePropertyChanged("ACTN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SyncCustomer {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.praxair.com.co/customer", Order=0)]
        public WCF_Customers.ServicioCustomerPraxReqABCSImp.CUSTOMERS CUSTOMERS;
        
        public SyncCustomer() {
        }
        
        public SyncCustomer(WCF_Customers.ServicioCustomerPraxReqABCSImp.CUSTOMERS CUSTOMERS) {
            this.CUSTOMERS = CUSTOMERS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SyncCustomerPraxReqABCSImplChannel : WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomerPraxReqABCSImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncCustomerPraxReqABCSImplClient : System.ServiceModel.ClientBase<WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomerPraxReqABCSImpl>, WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomerPraxReqABCSImpl {
        
        public SyncCustomerPraxReqABCSImplClient() {
        }
        
        public SyncCustomerPraxReqABCSImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncCustomerPraxReqABCSImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncCustomerPraxReqABCSImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncCustomerPraxReqABCSImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomerPraxReqABCSImpl.SyncCustomer(WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomer request) {
            base.Channel.SyncCustomer(request);
        }
        
        public void SyncCustomer(WCF_Customers.ServicioCustomerPraxReqABCSImp.CUSTOMERS CUSTOMERS) {
            WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomer inValue = new WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomer();
            inValue.CUSTOMERS = CUSTOMERS;
            ((WCF_Customers.ServicioCustomerPraxReqABCSImp.SyncCustomerPraxReqABCSImpl)(this)).SyncCustomer(inValue);
        }
    }
}
