//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.225
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.225.
// 
#pragma warning disable 1591

namespace AppDisparadorCustomers.ServicioCustomers {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWS_Customers", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WS_Customers : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConfirmationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_CustomersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Customers() {
            this.Url = global::AppDisparadorCustomers.Properties.Settings.Default.AppDisparadorCustomers_ServicioCustomers_WS_Customers;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConfirmationCompletedEventHandler ConfirmationCompleted;
        
        /// <remarks/>
        public event Get_CustomersCompletedEventHandler Get_CustomersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.praxair.com.co/customer/IWS_Customers/Confirmation", RequestNamespace="http://www.praxair.com.co/customer", ResponseNamespace="http://www.praxair.com.co/customer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] Confirmation(int companyID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool companyIDSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string interfaceStatus, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string an8) {
            object[] results = this.Invoke("Confirmation", new object[] {
                        companyID,
                        companyIDSpecified,
                        customerID,
                        interfaceStatus,
                        an8});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmationAsync(int companyID, bool companyIDSpecified, string customerID, string interfaceStatus, string an8) {
            this.ConfirmationAsync(companyID, companyIDSpecified, customerID, interfaceStatus, an8, null);
        }
        
        /// <remarks/>
        public void ConfirmationAsync(int companyID, bool companyIDSpecified, string customerID, string interfaceStatus, string an8, object userState) {
            if ((this.ConfirmationOperationCompleted == null)) {
                this.ConfirmationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmationOperationCompleted);
            }
            this.InvokeAsync("Confirmation", new object[] {
                        companyID,
                        companyIDSpecified,
                        customerID,
                        interfaceStatus,
                        an8}, this.ConfirmationOperationCompleted, userState);
        }
        
        private void OnConfirmationOperationCompleted(object arg) {
            if ((this.ConfirmationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmationCompleted(this, new ConfirmationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.praxair.com.co/customer/IWS_Customers/Get_Customers", RequestNamespace="http://www.praxair.com.co/customer", ResponseNamespace="http://www.praxair.com.co/customer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] Get_Customers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string interfaceStatus) {
            object[] results = this.Invoke("Get_Customers", new object[] {
                        interfaceStatus});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_CustomersAsync(string interfaceStatus) {
            this.Get_CustomersAsync(interfaceStatus, null);
        }
        
        /// <remarks/>
        public void Get_CustomersAsync(string interfaceStatus, object userState) {
            if ((this.Get_CustomersOperationCompleted == null)) {
                this.Get_CustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_CustomersOperationCompleted);
            }
            this.InvokeAsync("Get_Customers", new object[] {
                        interfaceStatus}, this.Get_CustomersOperationCompleted, userState);
        }
        
        private void OnGet_CustomersOperationCompleted(object arg) {
            if ((this.Get_CustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_CustomersCompleted(this, new Get_CustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConfirmationCompletedEventHandler(object sender, ConfirmationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get_CustomersCompletedEventHandler(object sender, Get_CustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_CustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_CustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591